// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dt_create
SEXP dt_create(int depth);
RcppExport SEXP _VectorForgeML_dt_create(SEXP depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_create(depth));
    return rcpp_result_gen;
END_RCPP
}
// dt_fit
void dt_fit(SEXP ptr, NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_dt_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    dt_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// dt_predict
NumericVector dt_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_dt_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// kmeans_create
SEXP kmeans_create(int k);
RcppExport SEXP _VectorForgeML_kmeans_create(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_create(k));
    return rcpp_result_gen;
END_RCPP
}
// kmeans_fit
void kmeans_fit(SEXP ptr, NumericMatrix X, int max_iter);
RcppExport SEXP _VectorForgeML_kmeans_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    kmeans_fit(ptr, X, max_iter);
    return R_NilValue;
END_RCPP
}
// kmeans_predict
IntegerVector kmeans_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_kmeans_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// knn_create
SEXP knn_create(int k, int mode);
RcppExport SEXP _VectorForgeML_knn_create(SEXP kSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_create(k, mode));
    return rcpp_result_gen;
END_RCPP
}
// knn_fit
void knn_fit(SEXP ptr, NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_knn_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    knn_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// knn_predict
NumericVector knn_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_knn_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// lr_create
SEXP lr_create();
RcppExport SEXP _VectorForgeML_lr_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(lr_create());
    return rcpp_result_gen;
END_RCPP
}
// lr_fit
void lr_fit(SEXP ptr, NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_lr_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    lr_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// lr_predict
NumericVector lr_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_lr_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(lr_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// fastLm
NumericVector fastLm(NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_fastLm(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastLm(X, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_fit_transform
List cpp_scale_fit_transform(NumericMatrix X, double eps);
RcppExport SEXP _VectorForgeML_cpp_scale_fit_transform(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_fit_transform(X, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_scale_transform
NumericMatrix cpp_scale_transform(NumericMatrix X, NumericVector means, NumericVector sds, double eps);
RcppExport SEXP _VectorForgeML_cpp_scale_transform(SEXP XSEXP, SEXP meansSEXP, SEXP sdsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sds(sdsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_scale_transform(X, means, sds, eps));
    return rcpp_result_gen;
END_RCPP
}
// cpp_drop_constant_cols
List cpp_drop_constant_cols(NumericMatrix X, double eps);
RcppExport SEXP _VectorForgeML_cpp_drop_constant_cols(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_drop_constant_cols(X, eps));
    return rcpp_result_gen;
END_RCPP
}
// logreg_create
SEXP logreg_create();
RcppExport SEXP _VectorForgeML_logreg_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(logreg_create());
    return rcpp_result_gen;
END_RCPP
}
// logreg_fit
void logreg_fit(SEXP ptr, NumericMatrix X, NumericVector y, double lr, int epochs);
RcppExport SEXP _VectorForgeML_logreg_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lrSEXP, SEXP epochsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    logreg_fit(ptr, X, y, lr, epochs);
    return R_NilValue;
END_RCPP
}
// logreg_predict
NumericVector logreg_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_logreg_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logreg_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// logreg_predict_proba
NumericVector logreg_predict_proba(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_logreg_predict_proba(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(logreg_predict_proba(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// pca_create
SEXP pca_create(int ncomp);
RcppExport SEXP _VectorForgeML_pca_create(SEXP ncompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ncomp(ncompSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_create(ncomp));
    return rcpp_result_gen;
END_RCPP
}
// pca_fit
void pca_fit(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_pca_fit(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    pca_fit(ptr, X);
    return R_NilValue;
END_RCPP
}
// pca_transform
NumericMatrix pca_transform(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_pca_transform(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_transform(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// rf_create
SEXP rf_create(int ntrees, int depth, int mtry, bool cls);
RcppExport SEXP _VectorForgeML_rf_create(SEXP ntreesSEXP, SEXP depthSEXP, SEXP mtrySEXP, SEXP clsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< int >::type depth(depthSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< bool >::type cls(clsSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_create(ntrees, depth, mtry, cls));
    return rcpp_result_gen;
END_RCPP
}
// rf_fit
void rf_fit(SEXP ptr, NumericMatrix X, NumericVector y);
RcppExport SEXP _VectorForgeML_rf_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rf_fit(ptr, X, y);
    return R_NilValue;
END_RCPP
}
// rf_predict
NumericVector rf_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_rf_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rf_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// ridge_create
SEXP ridge_create();
RcppExport SEXP _VectorForgeML_ridge_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ridge_create());
    return rcpp_result_gen;
END_RCPP
}
// ridge_fit
void ridge_fit(SEXP ptr, NumericMatrix X, NumericVector y, double lambda);
RcppExport SEXP _VectorForgeML_ridge_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    ridge_fit(ptr, X, y, lambda);
    return R_NilValue;
END_RCPP
}
// ridge_predict
NumericVector ridge_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_ridge_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// softmax_create
SEXP softmax_create();
RcppExport SEXP _VectorForgeML_softmax_create() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(softmax_create());
    return rcpp_result_gen;
END_RCPP
}
// softmax_fit
void softmax_fit(SEXP ptr, NumericMatrix X, IntegerVector y, double lr, int epochs);
RcppExport SEXP _VectorForgeML_softmax_fit(SEXP ptrSEXP, SEXP XSEXP, SEXP ySEXP, SEXP lrSEXP, SEXP epochsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    softmax_fit(ptr, X, y, lr, epochs);
    return R_NilValue;
END_RCPP
}
// softmax_predict
IntegerVector softmax_predict(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_softmax_predict(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_predict(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// softmax_predict_proba
NumericMatrix softmax_predict_proba(SEXP ptr, NumericMatrix X);
RcppExport SEXP _VectorForgeML_softmax_predict_proba(SEXP ptrSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_predict_proba(ptr, X));
    return rcpp_result_gen;
END_RCPP
}
// square_vec
NumericVector square_vec(NumericVector x);
RcppExport SEXP _VectorForgeML_square_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(square_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// sum2
int sum2(int x, int y);
RcppExport SEXP _VectorForgeML_sum2(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(sum2(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sum_squares
double cpp_sum_squares(int n);
RcppExport SEXP _VectorForgeML_cpp_sum_squares(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sum_squares(n));
    return rcpp_result_gen;
END_RCPP
}
// dot_product
double dot_product(NumericVector a, NumericVector b);
RcppExport SEXP _VectorForgeML_dot_product(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dot_product(a, b));
    return rcpp_result_gen;
END_RCPP
}
// cpp_set_blas_threads
void cpp_set_blas_threads();
RcppExport SEXP _VectorForgeML_cpp_set_blas_threads() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_set_blas_threads();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VectorForgeML_dt_create", (DL_FUNC) &_VectorForgeML_dt_create, 1},
    {"_VectorForgeML_dt_fit", (DL_FUNC) &_VectorForgeML_dt_fit, 3},
    {"_VectorForgeML_dt_predict", (DL_FUNC) &_VectorForgeML_dt_predict, 2},
    {"_VectorForgeML_kmeans_create", (DL_FUNC) &_VectorForgeML_kmeans_create, 1},
    {"_VectorForgeML_kmeans_fit", (DL_FUNC) &_VectorForgeML_kmeans_fit, 3},
    {"_VectorForgeML_kmeans_predict", (DL_FUNC) &_VectorForgeML_kmeans_predict, 2},
    {"_VectorForgeML_knn_create", (DL_FUNC) &_VectorForgeML_knn_create, 2},
    {"_VectorForgeML_knn_fit", (DL_FUNC) &_VectorForgeML_knn_fit, 3},
    {"_VectorForgeML_knn_predict", (DL_FUNC) &_VectorForgeML_knn_predict, 2},
    {"_VectorForgeML_lr_create", (DL_FUNC) &_VectorForgeML_lr_create, 0},
    {"_VectorForgeML_lr_fit", (DL_FUNC) &_VectorForgeML_lr_fit, 3},
    {"_VectorForgeML_lr_predict", (DL_FUNC) &_VectorForgeML_lr_predict, 2},
    {"_VectorForgeML_fastLm", (DL_FUNC) &_VectorForgeML_fastLm, 2},
    {"_VectorForgeML_cpp_scale_fit_transform", (DL_FUNC) &_VectorForgeML_cpp_scale_fit_transform, 2},
    {"_VectorForgeML_cpp_scale_transform", (DL_FUNC) &_VectorForgeML_cpp_scale_transform, 4},
    {"_VectorForgeML_cpp_drop_constant_cols", (DL_FUNC) &_VectorForgeML_cpp_drop_constant_cols, 2},
    {"_VectorForgeML_logreg_create", (DL_FUNC) &_VectorForgeML_logreg_create, 0},
    {"_VectorForgeML_logreg_fit", (DL_FUNC) &_VectorForgeML_logreg_fit, 5},
    {"_VectorForgeML_logreg_predict", (DL_FUNC) &_VectorForgeML_logreg_predict, 2},
    {"_VectorForgeML_logreg_predict_proba", (DL_FUNC) &_VectorForgeML_logreg_predict_proba, 2},
    {"_VectorForgeML_pca_create", (DL_FUNC) &_VectorForgeML_pca_create, 1},
    {"_VectorForgeML_pca_fit", (DL_FUNC) &_VectorForgeML_pca_fit, 2},
    {"_VectorForgeML_pca_transform", (DL_FUNC) &_VectorForgeML_pca_transform, 2},
    {"_VectorForgeML_rf_create", (DL_FUNC) &_VectorForgeML_rf_create, 4},
    {"_VectorForgeML_rf_fit", (DL_FUNC) &_VectorForgeML_rf_fit, 3},
    {"_VectorForgeML_rf_predict", (DL_FUNC) &_VectorForgeML_rf_predict, 2},
    {"_VectorForgeML_ridge_create", (DL_FUNC) &_VectorForgeML_ridge_create, 0},
    {"_VectorForgeML_ridge_fit", (DL_FUNC) &_VectorForgeML_ridge_fit, 4},
    {"_VectorForgeML_ridge_predict", (DL_FUNC) &_VectorForgeML_ridge_predict, 2},
    {"_VectorForgeML_softmax_create", (DL_FUNC) &_VectorForgeML_softmax_create, 0},
    {"_VectorForgeML_softmax_fit", (DL_FUNC) &_VectorForgeML_softmax_fit, 5},
    {"_VectorForgeML_softmax_predict", (DL_FUNC) &_VectorForgeML_softmax_predict, 2},
    {"_VectorForgeML_softmax_predict_proba", (DL_FUNC) &_VectorForgeML_softmax_predict_proba, 2},
    {"_VectorForgeML_square_vec", (DL_FUNC) &_VectorForgeML_square_vec, 1},
    {"_VectorForgeML_sum2", (DL_FUNC) &_VectorForgeML_sum2, 2},
    {"_VectorForgeML_cpp_sum_squares", (DL_FUNC) &_VectorForgeML_cpp_sum_squares, 1},
    {"_VectorForgeML_dot_product", (DL_FUNC) &_VectorForgeML_dot_product, 2},
    {"_VectorForgeML_cpp_set_blas_threads", (DL_FUNC) &_VectorForgeML_cpp_set_blas_threads, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_VectorForgeML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
