# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dt_create <- function(depth) {
    .Call(`_VectorForgeML_dt_create`, depth)
}

dt_fit <- function(ptr, X, y) {
    invisible(.Call(`_VectorForgeML_dt_fit`, ptr, X, y))
}

dt_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_dt_predict`, ptr, X)
}

kmeans_create <- function(k) {
    .Call(`_VectorForgeML_kmeans_create`, k)
}

kmeans_fit <- function(ptr, X, max_iter = 100L) {
    invisible(.Call(`_VectorForgeML_kmeans_fit`, ptr, X, max_iter))
}

kmeans_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_kmeans_predict`, ptr, X)
}

knn_create <- function(k, mode) {
    .Call(`_VectorForgeML_knn_create`, k, mode)
}

knn_fit <- function(ptr, X, y) {
    invisible(.Call(`_VectorForgeML_knn_fit`, ptr, X, y))
}

knn_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_knn_predict`, ptr, X)
}

lr_create <- function() {
    .Call(`_VectorForgeML_lr_create`)
}

lr_fit <- function(ptr, X, y) {
    invisible(.Call(`_VectorForgeML_lr_fit`, ptr, X, y))
}

lr_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_lr_predict`, ptr, X)
}

fastLm <- function(X, y) {
    .Call(`_VectorForgeML_fastLm`, X, y)
}

cpp_scale_fit_transform <- function(X, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_scale_fit_transform`, X, eps)
}

cpp_scale_transform <- function(X, means, sds, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_scale_transform`, X, means, sds, eps)
}

cpp_drop_constant_cols <- function(X, eps = 1e-12) {
    .Call(`_VectorForgeML_cpp_drop_constant_cols`, X, eps)
}

logreg_create <- function() {
    .Call(`_VectorForgeML_logreg_create`)
}

logreg_fit <- function(ptr, X, y, lr = 0.1, epochs = 100L) {
    invisible(.Call(`_VectorForgeML_logreg_fit`, ptr, X, y, lr, epochs))
}

logreg_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_logreg_predict`, ptr, X)
}

logreg_predict_proba <- function(ptr, X) {
    .Call(`_VectorForgeML_logreg_predict_proba`, ptr, X)
}

pca_create <- function(ncomp) {
    .Call(`_VectorForgeML_pca_create`, ncomp)
}

pca_fit <- function(ptr, X) {
    invisible(.Call(`_VectorForgeML_pca_fit`, ptr, X))
}

pca_transform <- function(ptr, X) {
    .Call(`_VectorForgeML_pca_transform`, ptr, X)
}

rf_create <- function(ntrees, depth, mtry, cls) {
    .Call(`_VectorForgeML_rf_create`, ntrees, depth, mtry, cls)
}

rf_fit <- function(ptr, X, y) {
    invisible(.Call(`_VectorForgeML_rf_fit`, ptr, X, y))
}

rf_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_rf_predict`, ptr, X)
}

ridge_create <- function() {
    .Call(`_VectorForgeML_ridge_create`)
}

ridge_fit <- function(ptr, X, y, lambda = 1.0) {
    invisible(.Call(`_VectorForgeML_ridge_fit`, ptr, X, y, lambda))
}

ridge_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_ridge_predict`, ptr, X)
}

softmax_create <- function() {
    .Call(`_VectorForgeML_softmax_create`)
}

softmax_fit <- function(ptr, X, y, lr = 0.1, epochs = 200L) {
    invisible(.Call(`_VectorForgeML_softmax_fit`, ptr, X, y, lr, epochs))
}

softmax_predict <- function(ptr, X) {
    .Call(`_VectorForgeML_softmax_predict`, ptr, X)
}

softmax_predict_proba <- function(ptr, X) {
    .Call(`_VectorForgeML_softmax_predict_proba`, ptr, X)
}

square_vec <- function(x) {
    .Call(`_VectorForgeML_square_vec`, x)
}

sum2 <- function(x, y) {
    .Call(`_VectorForgeML_sum2`, x, y)
}

cpp_sum_squares <- function(n) {
    .Call(`_VectorForgeML_cpp_sum_squares`, n)
}

dot_product <- function(a, b) {
    .Call(`_VectorForgeML_dot_product`, a, b)
}

cpp_set_blas_threads <- function() {
    invisible(.Call(`_VectorForgeML_cpp_set_blas_threads`))
}

